"use client";
import { useEffect, useMemo, useState } from "react";
import { Download, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { isAdmin } from "@/lib/school-data";
import { addChatDomain, BUILTIN_CHAT_DOMAINS, ChatConversation, ChatDomain, ChatMessage, ChatProfile, listChatProfiles, logAdminChatAction, removeChatDomain, subscribeAllConversations, subscribeChatDomains, subscribeMessages } from "@/lib/chat";

export function ChatAdminPage(){const{user}=useAuth();const[allowed,setAllowed]=useState<boolean|null>(null),[domains,setDomains]=useState<ChatDomain[]>([]),[conversations,setConversations]=useState<ChatConversation[]>([]),[profiles,setProfiles]=useState<ChatProfile[]>([]),[activeId,setActiveId]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[status,setStatus]=useState("");
useEffect(()=>{if(user)void isAdmin(user.uid).then(setAllowed).catch(()=>setAllowed(false));},[user]);
useEffect(()=>allowed?subscribeChatDomains(setDomains):undefined,[allowed]);useEffect(()=>allowed?subscribeAllConversations(setConversations):undefined,[allowed]);useEffect(()=>{if(allowed)void listChatProfiles().then(setProfiles);},[allowed]);useEffect(()=>{if(!activeId)return;void(user&&logAdminChatAction(user.uid,"view",activeId));return subscribeMessages(activeId,setMessages);},[activeId,user]);
const names=useMemo(()=>new Map(profiles.map(p=>[p.uid,p.name])),[profiles]);const active=conversations.find(c=>c.id===activeId);
async function addDomain(){if(!user)return;const value=window.prompt("School email domain, e.g. school.org");if(!value)return;try{await addChatDomain(value,user.uid);}catch(e){setStatus(e instanceof Error?e.message:"Could not add domain.");}}
function exportLog(){if(!active||!user)return;void logAdminChatAction(user.uid,"export",active.id);const lines=[`MStudy safeguarding chat log`, `Conversation: ${active.id}`,`Members: ${active.members.map(x=>`${names.get(x)||x} (${x})`).join(", ")}`,"",...messages.map(m=>`${names.get(m.senderUid)||m.senderUid}: ${m.text}`)];const blob=new Blob([lines.join("\n")],{type:"text/plain"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`mstudy-chat-${active.id}.txt`;a.click();URL.revokeObjectURL(url);}
if(allowed===null)return <section className="page"><p>Checking admin access…</p></section>;if(!allowed)return <section className="page"><div className="admin-lock"><ShieldCheck/><h1>Admin access required</h1></div></section>;
return <section className="page chat-page"><div className="page-head"><div><p className="eyebrow">Safeguarding</p><h1>Messaging Admin</h1><p>Manage approved school domains and review internal chats when required.</p></div></div>{status?<div className="notice">{status}</div>:null}<section className="admin-section"><div className="section-row"><div><h2 className="section-title">Allowed messaging domains</h2><p className="section-help">The two original SES domains are built in. Add more schools here without redeploying.</p></div><button className="text-button" onClick={addDomain}><Plus size={15}/> Add domain</button></div><div className="locator-prefix-grid">{[...BUILTIN_CHAT_DOMAINS,...domains.map(d=>d.domain).filter(d=>!(BUILTIN_CHAT_DOMAINS as readonly string[]).includes(d))].map(domain=><article key={domain}><strong>@{domain}</strong><span>{(BUILTIN_CHAT_DOMAINS as readonly string[]).includes(domain)?"Built in":"Admin added"}</span>{!(BUILTIN_CHAT_DOMAINS as readonly string[]).includes(domain)?<button className="icon-button danger" onClick={()=>removeChatDomain(domain)}><Trash2 size={14}/></button>:null}</article>)}</div></section><section className="admin-section"><div className="section-row"><div><h2 className="section-title">Safeguarding chat viewer</h2><p className="section-help">Admin views and exports are written to an audit log.</p></div>{active?<button className="secondary-button" onClick={exportLog}><Download size={15}/> Export chat log</button>:null}</div><div className="chat-layout"><aside className="chat-sidebar"><div className="chat-conversations">{conversations.map(c=><button key={c.id} className={activeId===c.id?"active":""} onClick={()=>setActiveId(c.id)}><strong>{c.type==="group"?c.title:c.members.map(x=>names.get(x)||"Student").join(" ↔ ")}</strong><small>{c.lastMessage||"No messages"}</small></button>)}</div></aside><main className="chat-thread">{active?<><header className="chat-thread-head"><div><strong>{active.type==="group"?active.title:"Direct message"}</strong><small>{active.members.map(x=>names.get(x)||x).join(", ")}</small></div></header><div className="chat-messages">{messages.map(m=><div className="chat-bubble" key={m.id}><small>{names.get(m.senderUid)||m.senderUid}</small><p>{m.text}</p></div>)}</div></>:<div className="chat-empty"><h2>Select a conversation</h2></div>}</main></div></section></section>}
