"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, CheckCircle2, Copy, Gamepad2, LogIn, Play, Radio, Sparkles, Trophy, X, XCircle } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { Note, subscribeCollection } from "@/lib/data";
import type { ClassroomAssignment, ClassroomCourse, ClassroomResource } from "@/lib/classroom";
import {
  advanceTeamRoom, createTeamRoom, finishTeamRoom, joinTeamRoom, processTeamAnswer, revealTeamResults,
  startTeamRoom, submitTeamAnswer, subscribeTeamAnswers, subscribeTeamPlayers, subscribeTeamRoom, subscribeTeamSecret,
  TeamAnswer, TeamPlayer, TeamQuestion, TeamRoom, TeamRoomSecret,
} from "@/lib/team-mode";

type DriveStudyFile = { id: string; title: string; extractedText?: string };
type SourceKind = "note" | "drive" | "assignment" | "resource" | "text";
type Screen = "home" | "host" | "join" | "room";
const STOP = new Set(["about","after","again","because","before","being","between","could","during","every","first","from","have","into","other","should","their","there","these","they","this","those","through","under","using","very","were","what","when","where","which","while","with","would","your"]);
function cleanWord(word:string){return word.replace(/[^A-Za-z0-9'-]/g,"").trim();}
function shuffle<T>(items:T[]){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function fallbackQuestions(text:string):TeamQuestion[]{const sentences=text.replace(/\s+/g," ").split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(s=>s.length>35);const pool=Array.from(new Set(text.split(/\s+/).map(cleanWord).filter(w=>w.length>=5&&!STOP.has(w.toLowerCase()))));const out:TeamQuestion[]=[];for(const sentence of sentences){const words=sentence.split(/\s+/).map(cleanWord).filter(w=>w.length>=5&&!STOP.has(w.toLowerCase()));if(!words.length)continue;const answer=words[Math.floor(words.length/2)];const distractors=shuffle(pool.filter(w=>w.toLowerCase()!==answer.toLowerCase())).slice(0,3);if(distractors.length<3)continue;const escaped=answer.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");out.push({id:`local-${out.length}`,prompt:sentence.replace(new RegExp(`\\b${escaped}\\b`,"i"),"_____"),choices:shuffle([answer,...distractors]),answer,explanation:sentence});if(out.length>=10)break;}return out;}
function extracted(materials?:{extractedText?:string}[]){return(materials||[]).map(m=>m.extractedText?.trim()||"").filter(Boolean).join("\n\n").trim();}

export function TeamModePage(){
  const {user}=useAuth();
  const [screen,setScreen]=useState<Screen>("home"),[code,setCode]=useState(""),[joinCode,setJoinCode]=useState(""),[displayName,setDisplayName]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [room,setRoom]=useState<TeamRoom|null>(null),[players,setPlayers]=useState<TeamPlayer[]>([]),[answers,setAnswers]=useState<TeamAnswer[]>([]),[secret,setSecret]=useState<TeamRoomSecret|null>(null),[picked,setPicked]=useState("");
  const [notes,setNotes]=useState<Note[]>([]),[assignments,setAssignments]=useState<ClassroomAssignment[]>([]),[resources,setResources]=useState<ClassroomResource[]>([]),[driveFiles,setDriveFiles]=useState<DriveStudyFile[]>([]),[courses,setCourses]=useState<ClassroomCourse[]>([]);
  const [sourceKind,setSourceKind]=useState<SourceKind>("note"),[sourceId,setSourceId]=useState(""),[pastedText,setPastedText]=useState("");
  const processing=useRef(new Set<string>());
  useEffect(()=>{if(user&&!displayName)setDisplayName((user.displayName||user.email?.split("@")[0]||"Player").slice(0,24));},[user,displayName]);
  useEffect(()=>user?subscribeCollection<Note>(user.uid,"notes",setNotes):undefined,[user]);
  useEffect(()=>user?subscribeCollection<ClassroomAssignment>(user.uid,"classroomAssignments",setAssignments,{orderByCreatedAt:false}):undefined,[user]);
  useEffect(()=>user?subscribeCollection<ClassroomResource>(user.uid,"classroomResources",setResources,{orderByCreatedAt:false}):undefined,[user]);
  useEffect(()=>user?subscribeCollection<DriveStudyFile>(user.uid,"driveStudyFiles",setDriveFiles,{orderByCreatedAt:false}):undefined,[user]);
  useEffect(()=>user?subscribeCollection<ClassroomCourse>(user.uid,"classroomCourses",setCourses,{orderByCreatedAt:false}):undefined,[user]);
  useEffect(()=>{if(!code)return;const a=subscribeTeamRoom(code,v=>{setRoom(v);if(!v){setScreen("home");setCode("");}}),b=subscribeTeamPlayers(code,setPlayers),c=subscribeTeamAnswers(code,setAnswers);return()=>{a();b();c();};},[code]);
  const isHost=Boolean(user&&room&&room.hostUid===user.uid);
  useEffect(()=>{if(!code||!isHost){setSecret(null);return;}return subscribeTeamSecret(code,setSecret);},[code,isHost]);
  useEffect(()=>setPicked(""),[room?.currentQuestionIndex]);
  useEffect(()=>{if(!isHost||!secret||!room||room.status!=="playing")return;answers.filter(a=>!a.processed&&!processing.current.has(a.id)).forEach(a=>{const q=secret.questions[a.questionIndex];if(!q)return;processing.current.add(a.id);void processTeamAnswer(code,a,q,room.questionStartedAt).finally(()=>processing.current.delete(a.id));});},[answers,isHost,secret,room,code]);
  const courseNames=useMemo(()=>new Map(courses.map(c=>[c.id,c.name])),[courses]);
  const selectedNote=notes.find(n=>n.id===sourceId),selectedDrive=driveFiles.find(f=>f.id===sourceId),selectedAssignment=assignments.find(i=>`${i.courseId}:${i.id}`===sourceId),selectedResource=resources.find(i=>`${i.courseId}:${i.id}`===sourceId);
  const sourceText=sourceKind==="note"?selectedNote?.content?.trim()||"":sourceKind==="drive"?selectedDrive?.extractedText?.trim()||"":sourceKind==="assignment"?extracted(selectedAssignment?.materials)||selectedAssignment?.description?.trim()||"":sourceKind==="resource"?extracted(selectedResource?.materials)||selectedResource?.description?.trim()||"":pastedText.trim();
  const title=sourceKind==="note"?selectedNote?.title||"Team study game":sourceKind==="drive"?selectedDrive?.title||"Team study game":sourceKind==="assignment"?selectedAssignment?.title||"Team study game":sourceKind==="resource"?selectedResource?.title||"Team study game":"Team study game";
  const subject=sourceKind==="note"?selectedNote?.subject||"Study":sourceKind==="assignment"?courseNames.get(selectedAssignment?.courseId||"")||"Classroom":sourceKind==="resource"?courseNames.get(selectedResource?.courseId||"")||"Classroom":sourceKind==="drive"?"Drive file":"Study material";
  const teamTotals=useMemo(()=>{const t={"Team A":0,"Team B":0};players.forEach(p=>t[p.team]+=p.score||0);return t;},[players]);
  const currentPlayer=players.find(p=>p.uid===user?.uid),currentAnswer=answers.find(a=>a.uid===user?.uid&&a.questionIndex===room?.currentQuestionIndex),alreadyAnswered=Boolean(currentAnswer);
  async function buildAndHost(){if(!user||sourceText.length<80)return;setBusy(true);setMessage("");let questions:TeamQuestion[]=[];try{const token=await user.getIdToken();const response=await fetch("/api/games/generate",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({title,subject,text:sourceText,questionMode:"mcq"})});const data=await response.json() as {questions?:Array<{prompt:string;choices:string[];answer:string;explanation?:string}>;error?:string};if(!response.ok||!data.questions?.length)throw new Error(data.error||"AI generation failed.");questions=data.questions.filter(q=>q.choices?.length>=2).map((q,i)=>({id:`team-${i}`,...q}));}catch(error){questions=fallbackQuestions(sourceText);setMessage(`${error instanceof Error?error.message:"Could not use AI."} Using MStudy's built-in generator.`);}if(questions.length<4){setBusy(false);setMessage("MStudy could not make enough questions. Try a longer source.");return;}try{const newCode=await createTeamRoom(user.uid,displayName||"Host",title,subject,questions);setCode(newCode);setScreen("room");}catch(error){setMessage(error instanceof Error?error.message:"Could not create room.");}finally{setBusy(false);}}
  async function join(){if(!user)return;setBusy(true);try{const joined=await joinTeamRoom(joinCode,user.uid,displayName||"Player");setCode(joined);setScreen("room");}catch(error){setMessage(error instanceof Error?error.message:"Could not join room.");}finally{setBusy(false);}}
  async function answer(choice:string){if(!user||!room||room.status!=="playing"||room.roundState!=="question"||alreadyAnswered)return;setPicked(choice);await submitTeamAnswer(code,user.uid,room.currentQuestionIndex,choice);}

  if(screen==="home")return <section className="page team-page"><div className="team-hero"><div><p className="eyebrow">Multiplayer study</p><h1>Team Mode</h1><p>Everyone answers the same question live, including the host. Correct answers earn points, with a speed bonus for faster responses.</p></div><Gamepad2 size={34}/></div><div className="team-grid"><article className="team-card"><h2>Host a game</h2><p>Create a live round from your study material.</p><button className="primary-button" onClick={()=>setScreen("host")}><Play size={17}/> Host Team Mode</button></article><article className="team-card"><h2>Join a game</h2><p>Enter a five-character code.</p><button className="secondary-button" onClick={()=>setScreen("join")}><LogIn size={17}/> Join with code</button></article></div></section>;
  if(screen==="host")return <section className="page team-page"><div className="page-head"><div><p className="eyebrow">Host Team Mode</p><h1>Build the round</h1></div><button className="icon-button" onClick={()=>setScreen("home")}><X size={18}/></button></div><article className="team-card"><div className="team-source-tabs">{(["note","drive","assignment","resource","text"] as SourceKind[]).map(kind=><button key={kind} className={sourceKind===kind?"active":""} onClick={()=>{setSourceKind(kind);setSourceId("");setPastedText("");}}>{kind==="note"?"Notes":kind==="drive"?"Drive":kind==="assignment"?"Assignments":kind==="resource"?"Class materials":"Paste text"}</button>)}</div><div className="team-form">{sourceKind==="note"?<label>Note<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose…</option>{notes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label>:null}{sourceKind==="drive"?<label>Drive file<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose…</option>{driveFiles.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select></label>:null}{sourceKind==="assignment"?<label>Assignment<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose…</option>{assignments.map(i=><option key={`${i.courseId}:${i.id}`} value={`${i.courseId}:${i.id}`}>{courseNames.get(i.courseId)||"Classroom"} · {i.title}</option>)}</select></label>:null}{sourceKind==="resource"?<label>Class material<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose…</option>{resources.map(i=><option key={`${i.courseId}:${i.id}`} value={`${i.courseId}:${i.id}`}>{courseNames.get(i.courseId)||"Classroom"} · {i.title}</option>)}</select></label>:null}{sourceKind==="text"?<label>Study material<textarea rows={9} value={pastedText} onChange={e=>setPastedText(e.target.value)}/></label>:null}<label>Your lobby name<input value={displayName} onChange={e=>setDisplayName(e.target.value.slice(0,24))}/></label></div><button className="primary-button" disabled={busy||sourceText.length<80} onClick={buildAndHost}><Sparkles size={17}/>{busy?"Building…":"Build game & create code"}</button>{message?<div className="team-warning">{message}</div>:null}</article></section>;
  if(screen==="join")return <section className="page team-page"><div className="page-head"><div><p className="eyebrow">Join Team Mode</p><h1>Enter the room code</h1></div><button className="icon-button" onClick={()=>setScreen("home")}><X size={18}/></button></div><article className="team-card team-form"><label>Join code<input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,5))}/></label><label>Your name<input value={displayName} onChange={e=>setDisplayName(e.target.value.slice(0,24))}/></label><button className="primary-button" disabled={busy||joinCode.length!==5} onClick={join}><LogIn size={17}/> Join game</button>{message?<div className="team-warning">{message}</div>:null}</article></section>;
  if(!room)return <section className="page"><p>Opening room…</p></section>;
  if(room.status==="lobby")return <section className="page team-page"><div className="team-hero"><div><span className="room-status"><Radio size={13}/> Lobby open</span><p className="eyebrow">Join code</p><div className="join-code">{room.code}</div><p>{room.title} · {room.subject}</p></div><div className="team-actions"><button className="secondary-button" onClick={()=>navigator.clipboard?.writeText(room.code)}><Copy size={16}/> Copy code</button>{isHost?<button className="primary-button" disabled={!secret?.questions.length} onClick={()=>secret&&startTeamRoom(code,secret.questions)}><Play size={17}/> Start game</button>:null}</div></div><div className="team-lobby"><article className="team-card"><h2>Players ({players.length})</h2><div className="player-list">{players.map(p=><div className="player-row" key={p.uid}><strong>{p.name}{p.uid===room.hostUid?" (Host)":""}</strong><span className="team-chip">{p.team}</span></div>)}</div></article><article className="team-card"><h2>Teams</h2><div className="leaderboard"><div className="team-score-card"><span>Team A</span><strong>{players.filter(p=>p.team==="Team A").length}</strong></div><div className="team-score-card"><span>Team B</span><strong>{players.filter(p=>p.team==="Team B").length}</strong></div></div></article></div></section>;
  if(room.status==="finished"){const winner=teamTotals["Team A"]===teamTotals["Team B"]?"It's a tie!":`${teamTotals["Team A"]>teamTotals["Team B"]?"Team A":"Team B"} wins!`;return <section className="page team-page"><article className="team-card team-results"><Trophy size={44}/><h1>{winner}</h1><div className="team-results-grid"><div className="team-score-card"><span>Team A</span><strong>{teamTotals["Team A"]}</strong></div><div className="team-score-card"><span>Team B</span><strong>{teamTotals["Team B"]}</strong></div></div><h2>Leaderboard</h2><div className="player-list">{[...players].sort((a,b)=>b.score-a.score).map((p,i)=><div className="player-row" key={p.uid}><span>#{i+1} {p.name} · {p.correct}/{p.answered}</span><strong>{p.score} pts</strong></div>)}</div></article></section>};
  const question=room.currentQuestion;
  if(room.roundState==="results")return <section className="page team-page"><div className="team-hero"><div><span className="room-status"><Radio size={13}/> Round results</span><p className="eyebrow">Question {room.currentQuestionIndex+1} / {room.questionCount}</p><h1>{room.revealedAnswer}</h1><p>{room.revealedExplanation}</p></div>{isHost?<button className="primary-button" onClick={()=>secret&&advanceTeamRoom(code,room.currentQuestionIndex,secret.questions)}>{room.currentQuestionIndex+1>=room.questionCount?"Finish game":"Next question"}<ArrowRight size={16}/></button>:<span className="team-chip">Waiting for host</span>}</div><div className="team-lobby"><article className="team-card"><h2>This question</h2><div className="player-list">{[...players].sort((a,b)=>{const aa=answers.find(x=>x.uid===a.uid&&x.questionIndex===room.currentQuestionIndex)?.points||0,bb=answers.find(x=>x.uid===b.uid&&x.questionIndex===room.currentQuestionIndex)?.points||0;return bb-aa;}).map(p=>{const a=answers.find(x=>x.uid===p.uid&&x.questionIndex===room.currentQuestionIndex);return <div className="player-row" key={p.uid}><span>{p.name}</span><strong>{a?.correct?<><CheckCircle2 size={14}/> +{a.points||0}</>:<><XCircle size={14}/> 0</>}</strong></div>})}</div></article><aside className="team-card"><h2>Leaderboard</h2><div className="player-list">{[...players].sort((a,b)=>b.score-a.score).map((p,i)=><div className="player-row" key={p.uid}><span>#{i+1} {p.name}</span><strong>{p.score}</strong></div>)}</div></aside></div></section>;
  return <section className="page team-page"><div className="team-hero"><div><span className="room-status"><Radio size={13}/> Live · {room.code}</span><p className="eyebrow">Question {room.currentQuestionIndex+1} / {room.questionCount}</p><h1>{room.title}</h1></div><div className="team-actions">{isHost?<><button className="secondary-button" onClick={()=>finishTeamRoom(code)}>End game</button><button className="primary-button" disabled={!secret} onClick={()=>secret&&revealTeamResults(code,room.currentQuestionIndex,secret.questions)}>Show results</button></>:<span className="team-chip">{currentPlayer?.team}</span>}</div></div><div className="team-lobby"><article className="team-card team-question"><h2>{question?.prompt||"Loading question…"}</h2><div className="team-choice-grid">{question?.choices.map(choice=><button className={picked===choice?"team-choice selected":"team-choice"} key={choice} disabled={alreadyAnswered} onClick={()=>answer(choice)}>{choice}</button>)}</div>{alreadyAnswered?<div className="team-warning">{currentAnswer?.processed?(currentAnswer.correct?`Correct! +${currentAnswer.points||0} points`:`Not quite. 0 points`):"Answer locked in…"}</div>:<p className="section-help">Answer quickly: correct answers are worth 100 points plus up to 100 speed-bonus points.</p>}</article><aside className="team-card"><h2>Live score</h2><div className="leaderboard"><div className="team-score-card"><span>Team A</span><strong>{teamTotals["Team A"]}</strong></div><div className="team-score-card"><span>Team B</span><strong>{teamTotals["Team B"]}</strong></div></div><h3>Locked in</h3><p>{answers.filter(a=>a.questionIndex===room.currentQuestionIndex).length} / {players.length} answered</p></aside></div></section>;
}
